"""added column slug ti news table

Revision ID: a4d564bdb20a
Revises: 97f313d0809f
Create Date: 2026-09-20 14:19:01.358353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d564bdb20a'
down_revision: Union[str, Sequence[str], None] = '97f313d0809f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('slug', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'slug')
    # ### end Alembic commands ###
